package com.nbamanager.web.dto;

public record PlayerDto(
        Long id,
        Long nbaPlayerId,
        String name,
        String nameEn,
        String translationStatus,
        Long teamId,
        String teamName,
        String position,
        Double pointsPerGame,
        Double reboundsPerGame,
        Double assistsPerGame,
        Double stealsPerGame,
        Integer gamesPlayed,
        Double minutesPerGame,
        Double fieldGoalPct,
        Double threePointPct,
        Double freeThrowPct,
        Double blocksPerGame,
        Double turnoversPerGame,
        Double efficiency,
        Double trueShootingPct,
        Double usagePct,
        String jerseyNumber,
        String height,
        Integer weight,
        String country,
        Double per,
        Double winShares,
        Double vorp,
        Double bpm,
        Double offensiveRating,
        Double defensiveRating) {}
